Repository open-dicom/awesome-dicom, pull requests merged in 2023-03, with the labels that each got.

#4 Fixed "Machine Learning" header level
  readme.md
Labels: fix

#6 Fixed "Machine Learning" header level in TOC
  readme.md
Labels: fix

#8 Added 'Image Computing Platforms' header to TOC
  readme.md
Labels: fix

#10 Fixed DICOMautomaton list item key
  readme.md
Labels: fix

#12 Styling fixes
  readme.md
Labels: enhancement

#2 Add VolView item to Javascript Visualization
  readme.md
Labels: new entry
